### ISSUE TITLE
Suggestions for the Target User Description

### ISSUE THREAD

**Issue by tshradheya** [CS2103AUG2017-W14-B1/main#78]
> Please include a few lines/paragraph in the introductory section of your developer guide explaining the target user profile.

We need to this by tonight. Can give some suggestions as to what can we write in this considering the fact that we are focusing on `University Students`

**Comment by justinpoh** [comment]
This application is targeted towards University students, aiming to meet their needs throughout their University life, and hopefully beyond.
We are targeting students that needs to be able to tag contacts and perform searches using tags. This is necessary as students often have to form groups in their modules during project work, and tagging allows them to clearly label contacts appropriately. Searching contacts using tags would also allow faster and more focused searches.
Some students, such as Teaching Assistants or member of a committee, might need to send bulk emails to specific groups of people. Hence, we are aiming to meet this need by allowing users to send email to a group of contacts specified by their tags.
University is also the place to build connections, and one way this is achieved is by sharing contacts with others. We aim to make this sharing process easier by allowing users to export and import data files containing contacts and merge it with their existing data file. Users are also allowed to choose the contacts that they want to export by specifying tags.

**Comment by chuaweiwen** [comment]
University students meet a lot of people in the university, such as project group members, tutors, lecturers, friends and other connections. Nowadays it is important for students to build connections with other people, as connections may also help students for their future career after graduation. Since the students meet a lot of people, they may not be able to remember all the information about the people they met. Therefore, iContacts aims to help students to store and manage their contacts easily.

Students will be able to search for contacts easily by finding the name. Students may also able to tag their contacts so that they may also find these contacts by searching for their tag. iContacts also allows students to export or import contact information so that students can share these information, or serve as a back-up.

**Comment by justinpoh** [comment]
Bullet point style seems clearer

Target User Profile:

- Student
- Need to form teams in different modules
- Need to send bulk emails to a group of people
- Need to be able to share contacts
- Regularly meet new people (tutors, lecturers, other students)

Needs

- Label/tag contacts for easy identification/search
- Send bulk email to a group of people
- Able to select contacts to export
- Import contacts from another data file and merge with current data file if needed
